version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ditoischallengingme
      POSTGRES_DB: ditochallenge
  server:
    build: server/
    command: npm start
    ports:
      - "3001:3001"
    links:
      - postgres
  client:
    build: client/
    command: npm run dev
    ports:
      - "3000:3000"
    links:
      - server
